# Basic Python

## 1. Split this string

In [10]:
s = "Hi there Sam!"
x = s.split()
print(x)

['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742


In [17]:
planet = "Earth"
diameter = 12742
text = ( 'The diameter of {} is {} kilometers.'.format(planet,diameter))
print("\x1B[3m" + text + "\x1B[0m")

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
a=lst[3][1][2];
print(a)

['hello']


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [21]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array) 

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [25]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate((a, b), axis=0))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [31]:
import pandas as pd
data = [['tom', 10], ['nick', 15], ['juli', 14]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
df


Name  Age
0   tom   10
1  nick   15
2  juli   14

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [36]:
import pandas as pd 
startDate = "1st Jan, 2023"
endDate = "10th Feb, 2023"
dates = pd.date_range(startDate, endDate).strftime("%d %b, %Y").tolist()
print(dates)

['01 Jan, 2023', '02 Jan, 2023', '03 Jan, 2023', '04 Jan, 2023', '05 Jan, 2023', '06 Jan, 2023', '07 Jan, 2023', '08 Jan, 2023', '09 Jan, 2023', '10 Jan, 2023', '11 Jan, 2023', '12 Jan, 2023', '13 Jan, 2023', '14 Jan, 2023', '15 Jan, 2023', '16 Jan, 2023', '17 Jan, 2023', '18 Jan, 2023', '19 Jan, 2023', '20 Jan, 2023', '21 Jan, 2023', '22 Jan, 2023', '23 Jan, 2023', '24 Jan, 2023', '25 Jan, 2023', '26 Jan, 2023', '27 Jan, 2023', '28 Jan, 2023', '29 Jan, 2023', '30 Jan, 2023', '31 Jan, 2023', '01 Feb, 2023', '02 Feb, 2023', '03 Feb, 2023', '04 Feb, 2023', '05 Feb, 2023', '06 Feb, 2023', '07 Feb, 2023', '08 Feb, 2023', '09 Feb, 2023', '10 Feb, 2023']


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [40]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns = ['S.No', 'Items', 'Value'])
print(df)

   S.No Items  Value
0     1   aaa     22
1     2   bbb     25
2     3   ccc     24
